<!DOCTYPE html>
<html>
    <?php 
        $file=basename(__FILE__, '.php');
        /* $file= "C. Panel"; */ // Panel de Administador SOLO
        $far="../";//Distancia para llegar a la general.
        include $far.'php/comun/head.php';//CAMBIAR RUTA SEGUN UBI
    ?>  
    <body class='bg-light <?php if($trabajador){echo " admin_body' id='body-pd";}?>'>
        <?php include_once $far.'content/header.php'; ?>
        <div class="term-bd">
            <br><h2><b>TÉRMINOS DEL SERVICIO</b><h2><br>
            <h3><b>GENERALIDADES</b><h3><br>

            <div class="term">
                <p>CONFID gestiona este sitio web. En todo el sitio, los t&eacute;rminos "nosotros", "nos" y "nuestro" se refieren en lo sucesivo a CONFID. CONFID ofrece esta p&aacute;gina web, incluida toda la informaci&oacute;n, las herramientas y los servicios que se ponen en este sitio a disposici&oacute;n suya, el usuario, siempre y cuando acepte la totalidad de los t&eacute;rminos, condiciones, pol&iacute;ticas y avisos contemplados aqu&iacute;.</p>
                <p>Al visitar nuestro sitio y/o comprarnos algo, usted interact&uacute;a con nuestro "Servicio" y reconoce como vinculantes los siguientes t&eacute;rminos y condiciones (denominados en lo sucesivo "T&eacute;rminos del servicio", "T&eacute;rminos"), incluidos aquellos t&eacute;rminos y condiciones adicionales y las pol&iacute;ticas que se mencionan aqu&iacute; y/o disponibles por medio de hiperv&iacute;nculo. Estos T&eacute;rminos del servicio se aplican a todos los usuarios del sitio, incluyendo de manera enunciativa mas no limitativa los usuarios que son navegadores, proveedores, clientes, comerciantes y/o que aporten contenido.</p>
                <p>Lea estos T&eacute;rminos del servicio detenidamente antes de acceder o utilizar nuestra p&aacute;gina web. Al acceder o utilizar cualquier parte del sitio, usted acepta estos T&eacute;rminos del servicio. Si no acepta la totalidad de los t&eacute;rminos y condiciones de este acuerdo, no podr&aacute; acceder al sitio web ni utilizar ning&uacute;n servicio. Si estos T&eacute;rminos del servicio se considerasen una oferta, la aceptaci&oacute;n se limita expresamente a los presentes T&eacute;rminos del servicio.</p>
                <p>Las nuevas funciones o herramientas que se agreguen a la tienda actual tambi&eacute;n estar&aacute;n sujetas a los T&eacute;rminos del servicio. Puede revisar la versi&oacute;n m&aacute;s reciente de los T&eacute;rminos del servicio en cualquier momento en esta p&aacute;gina. Nos reservamos el derecho de actualizar, cambiar o reemplazar cualquier parte de los presentes T&eacute;rminos del servicio mediante la publicaci&oacute;n de actualizaciones o cambios en nuestra p&aacute;gina web. Es su responsabilidad revisar esta p&aacute;gina peri&oacute;dicamente para ver los cambios. Su uso de la p&aacute;gina web o el acceso a ella de forma continuada despu&eacute;s de la publicaci&oacute;n de cualquier cambio constituye la aceptaci&oacute;n de dichos cambios.</p>
                <p>Nuestra tienda est&aacute; alojada en Casa del Jowi. Nos proporcionan la plataforma de comercio electr&oacute;nico en l&iacute;nea que nos permite venderle nuestros productos y servicios.</p>
                <br>                
                <p><strong>SECCI&Oacute;N 1: T&Eacute;RMINOS DE LA TIENDA ONLINE</strong></p>
                <p>Al aceptar los presentes T&eacute;rminos del servicio, usted declara que tiene la mayor&iacute;a de edad en su estado o provincia de residencia, o que es mayor de edad en su estado o provincia de residencia y que nos ha dado su consentimiento para permitir que cualquiera de las personas menores que dependen de usted utilice este sitio.</p>
                <p>No puede utilizar nuestros productos para ning&uacute;n fin ilegal o no autorizado ni puede, al hacer uso del Servicio, infringir las leyes de su jurisdicci&oacute;n (incluyendo de manera enunciativa m&aacute;s no limitativa, las leyes de derechos de autor).</p>
                <p>No transmitir&aacute; ning&uacute;n gusano o virus inform&aacute;ticos ni ning&uacute;n c&oacute;digo de naturaleza destructiva.</p>
                <p>El incumplimiento o violaci&oacute;n de cualquiera de los T&eacute;rminos dar&aacute; como resultado la rescisi&oacute;n inmediata de sus Servicios.</p>
                <br>
                <p><strong>SECCI&Oacute;N 2: CONDICIONES GENERALES</strong></p>
                <p>Nos reservamos el derecho de rechazar el servicio a cualquier persona, por cualquier motivo, en cualquier momento.</p>
                <p>Usted comprende que su contenido (sin incluir la informaci&oacute;n de la tarjeta de cr&eacute;dito) puede transferirse sin cifrar e implicar (a) transmisiones en varias redes; y (b) cambios para adaptarse a los requisitos t&eacute;cnicos de conexi&oacute;n de redes o dispositivos y cumplir con ellos. La informaci&oacute;n de la tarjeta de cr&eacute;dito siempre se cifra durante la transferencia a trav&eacute;s de las redes.</p>
                <p>Usted acepta no reproducir, duplicar, copiar, vender, revender ni aprovechar ninguna parte del Servicio, uso del Servicio o acceso al Servicio o cualquier contacto en el sitio web a trav&eacute;s de la cual se presta el servicio, sin nuestro permiso expreso por escrito.</p>
                <p>Los encabezados utilizados en este acuerdo se incluyen solo para facilitar la lectura y no limitar&aacute;n ni afectar&aacute;n los presentes T&eacute;rminos.</p>
                <br>
                <p><strong>SECCI&Oacute;N 3: EXACTITUD, TOTALIDAD Y CRONOLOG&Iacute;A DE LA INFORMACI&Oacute;N</strong></p>
                <p>No nos responsabilizamos si la informaci&oacute;n disponible en este sitio no es precisa, completa o actualizada. El material presentado en este sitio se proporciona solo para informaci&oacute;n general y no se debe confiar en &eacute;l ni utilizarlo como la &uacute;nica base para tomar decisiones sin consultar fuentes de informaci&oacute;n principales, m&aacute;s precisas, m&aacute;s completas o m&aacute;s recientes. Al confiar en cualquier material de este sitio lo hace por su cuenta y riesgo.</p>
                <p>Este sitio puede contener cierta informaci&oacute;n hist&oacute;rica. La informaci&oacute;n hist&oacute;rica, inevitablemente, no es actual y se proporciona &uacute;nicamente como referencia. Nos reservamos el derecho de modificar el contenido de este sitio en cualquier momento, pero no tenemos la obligaci&oacute;n de actualizar ninguna informaci&oacute;n en nuestro sitio. Usted acepta que es su responsabilidad controlar los cambios en nuestro sitio.</p>
                <br>
                <p><strong>SECCI&Oacute;N 4: MODIFICACIONES AL SERVICIO Y PRECIOS</strong></p>
                <p>Los precios de nuestros productos est&aacute;n sujetos a cambios sin previo aviso.</p>
                <p>Nos reservamos el derecho de modificar o discontinuar el Servicio (o cualquier parte o contenido del mismo) sin previo aviso en cualquier momento.</p>
                <p>No seremos responsables ante usted ni ante ning&uacute;n tercero por ninguna modificaci&oacute;n, cambio de precio, suspensi&oacute;n o interrupci&oacute;n del Servicio.</p>
                <br>
                <p><strong>SECCI&Oacute;N 5: PRODUCTOS O SERVICIOS (si corresponde)</strong></p>
                <p>Ciertos productos o servicios pueden estar disponibles exclusivamente online a trav&eacute;s del sitio web. Estos productos o servicios pueden tener cantidades limitadas y est&aacute;n sujetos a devoluci&oacute;n o cambio solo de acuerdo con nuestra Pol&iacute;tica de devoluci&oacute;n.</p>
                <p>Hemos hecho todo lo viable para mostrar con la mayor precisi&oacute;n posible los colores y las im&aacute;genes de nuestros productos que aparecen en la tienda. No podemos garantizar que la visualizaci&oacute;n de cualquier color en el monitor de su computadora sea precisa.</p>
                <p>Nos reservamos el derecho, pero no estamos obligados, de limitar las ventas de nuestros productos o servicios a cualquier persona, regi&oacute;n geogr&aacute;fica o jurisdicci&oacute;n. Podemos ejercer este derecho caso por caso. Nos reservamos el derecho de limitar las cantidades de cualquier producto o servicio que ofrecemos. Todas las descripciones de los productos o los precios de los productos est&aacute;n sujetos a cambios en cualquier momento y sin previo aviso, a nuestra entera discreci&oacute;n. Nos reservamos el derecho de discontinuar cualquier producto en cualquier momento. Cualquier oferta de cualquier producto o servicio que se realice en este sitio no tiene validez donde dicho producto o servicio est&eacute; prohibido.</p>
                <p>No garantizamos que la calidad de cualquier producto, servicio, informaci&oacute;n u otro material que usted haya comprado u obtenido cumplir&aacute; con sus expectativas, o que cualquier error en el Servicio se corregir&aacute;.</p>
                <br>
                <p><strong>SECCI&Oacute;N 6: EXACTITUD DE LA FACTURACI&Oacute;N Y DE LA INFORMACI&Oacute;N DE LA CUENTA</strong></p>
                <p>Nos reservamos el derecho de rechazar cualquier pedido que realice en nuestra tienda. Podemos, a nuestro exclusivo criterio, limitar o cancelar las cantidades compradas por persona, por hogar o por pedido. Estas restricciones pueden incluir pedidos realizados con la misma cuenta de cliente, la misma tarjeta de cr&eacute;dito o pedidos que usen la misma direcci&oacute;n de facturaci&oacute;n o de env&iacute;o. En el caso de que realicemos un cambio o cancelemos un pedido, intentaremos notificarle v&iacute;a correo electr&oacute;nico o la direcci&oacute;n de facturaci&oacute;n / n&uacute;mero de tel&eacute;fono proporcionados en el momento en que se realiz&oacute; el pedido. Nos reservamos el derecho de limitar o prohibir los pedidos que, a nuestra entera discreci&oacute;n, parezcan haber sido realizados por comerciantes, revendedores o distribuidores.</p>
                <p>Usted acepta suministrar informaci&oacute;n completa y precisa de la compra y cuenta actual, para todas las compras realizadas en nuestra tienda. Usted acepta actualizar r&aacute;pidamente su cuenta y dem&aacute;s informaciones, entre ellas, su direcci&oacute;n de correo electr&oacute;nico, los n&uacute;meros de tarjeta de cr&eacute;dito y las fechas de vencimiento, para que podamos completar sus transacciones y contactarlo seg&uacute;n sea necesario.</p>
                <p>Para obtener m&aacute;s informaci&oacute;n, consulte nuestra Pol&iacute;tica de devoluciones.</p>
                <br>
                <p><strong>SECCI&Oacute;N 7: HERRAMIENTAS OPCIONALES</strong></p>
                <p>Podemos proporcionarle acceso a herramientas de terceros que no supervisamos, ni tenemos ning&uacute;n control sobre ellas, ni tampoco contribuimos.</p>
                <p>Usted reconoce y acepta que brindamos acceso a dichas herramientas "tal como se encuentran" y "seg&uacute;n disponibilidad" sin garant&iacute;as, representaciones ni condiciones de ning&uacute;n tipo y sin ning&uacute;n tipo de respaldo. No tendremos ninguna responsabilidad como consecuencia del uso que haga de herramientas opcionales de terceros o en relaci&oacute;n a ellas.</p>
                <p>Cualquier uso que haga de las herramientas opcionales ofrecidas a trav&eacute;s del sitio es por su cuenta y riesgo, y debe asegurarse de estar familiarizado con los t&eacute;rminos seg&uacute;n los cuales los proveedores externos relevantes suministran dichas herramientas y aprobarlos.</p>
                <p>Tambi&eacute;n podemos, en el futuro, ofrecer nuevos servicios o funciones a trav&eacute;s del sitio web (incluido el lanzamiento de nuevas herramientas y recursos). Estas nuevas funciones o servicios tambi&eacute;n estar&aacute;n sujetos a los presentes T&eacute;rminos de servicio.</p>
                <br>
                <p><strong>SECCI&Oacute;N 8: ENLACES DE TERCEROS</strong></p>
                <p>Algunos contenidos, productos y servicios disponibles a trav&eacute;s de nuestro Servicio pueden incluir recursos de terceros.</p>
                <p>Los enlaces de terceros en este sitio pueden dirigirlo a p&aacute;ginas web de terceros que no est&aacute;n afiliados a nosotros. No somos responsables de examinar o evaluar el contenido o la exactitud, ni garantizamos ni asumiremos ninguna obligaci&oacute;n ni responsabilidad por los recursos o p&aacute;ginas web de terceros, ni por ning&uacute;n otro material, producto o servicio de terceros.</p>
                <p>No somos responsables de ning&uacute;n da&ntilde;o o perjuicio relacionado con la compra o el uso de bienes, servicios, recursos, contenido o cualquier otra transacci&oacute;n realizada en conexi&oacute;n con sitios web de terceros. Revise cuidadosamente las pol&iacute;ticas y pr&aacute;cticas de terceros, y aseg&uacute;rese de comprenderlas antes de participar en cualquier transacci&oacute;n. Las quejas, reclamos, inquietudes o preguntas referentes a productos de terceros deben dirigirse a estos.</p>
                <br>
                <p><strong>SECCI&Oacute;N 9: COMENTARIOS DE LOS USUARIOS, OPINIONES Y OTRAS COMUNICACIONES</strong></p>
                <p>Si, a petici&oacute;n nuestra, usted env&iacute;a ciertas comunicaciones espec&iacute;ficas (por ejemplo, participaciones en un concurso) o, sin una solicitud nuestra, env&iacute;a ideas creativas, sugerencias, propuestas, planes u otros materiales, ya sea online, por correo electr&oacute;nico, por correo postal, o de otro modo (denominado en lo sucesivo y de manera colectiva, 'comentarios'), usted acepta que podemos, en cualquier momento, sin restricci&oacute;n: editar, copiar, publicar, distribuir, traducir y usar en cualquier medio cualquier comentario que usted nos env&iacute;e. No tenemos ni tendremos ninguna obligaci&oacute;n (1) de mantener ning&uacute;n comentario de manera confidencial; (2) pagar alguna compensaci&oacute;n por cualquier comentario; o (3) responder a cualquier comentario.</p>
                <p>Podemos, pero no tenemos la obligaci&oacute;n de monitorear, editar o eliminar contenido que a nuestra entera discreci&oacute;n determinemos que es ilegal, ofensivo, amenazante, calumnioso, difamatorio, pornogr&aacute;fico, obsceno u objetable, o que infrinja la propiedad intelectual de cualquiera de las partes o de los presentes T&eacute;rminos del servicio.</p>
                <p>Usted acepta que sus comentarios no infringir&aacute;n ning&uacute;n derecho de terceros, incluidos los derechos de autor, marca registrada, privacidad, personalidad u otro derecho personal o de propiedad. Adem&aacute;s, acepta que sus comentarios no contendr&aacute;n material difamatorio, ileg&iacute;timo, abusivo u obsceno, ni contendr&aacute;n ning&uacute;n virus inform&aacute;tico ni otro software da&ntilde;ino que pueda afectar de cualquier manera el funcionamiento del Servicio o de cualquier sitio web relacionado. No puede utilizar una direcci&oacute;n de correo electr&oacute;nico falsa, simular ser otra persona o enga&ntilde;arnos o enga&ntilde;ar a terceros sobre el origen de los comentarios. Usted es el &uacute;nico responsable de los comentarios que realice y de su exactitud. No asumimos ninguna responsabilidad ni ninguna obligaci&oacute;n por los comentarios publicados por usted o por un tercero.</p>
                <br><p><strong>SECCI&Oacute;N 10: INFORMACI&Oacute;N PERSONAL</strong></p>
                <p>El env&iacute;o de la informaci&oacute;n personal que haga a trav&eacute;s de la tienda se rige por nuestra Pol&iacute;tica de privacidad. Para ver nuestra Pol&iacute;tica de privacidad.</p>
                <br>
                <p><strong>SECCI&Oacute;N 11: ERRORES, INEXACTITUDES Y OMISIONES</strong></p>
                <p>Puede haber informaci&oacute;n en nuestro sitio o en el Servicio que, ocasionalmente, contenga errores tipogr&aacute;ficos, inexactitudes u omisiones que puedan relacionarse con descripciones de productos, precios, promociones, ofertas, cargos por env&iacute;o de productos, tiempos de tr&aacute;nsito y disponibilidad. Nos reservamos el derecho de corregir cualquier error, inexactitud u omisi&oacute;n, de cambiar o actualizar informaci&oacute;n, o cancelar pedidos si alguna informaci&oacute;n en el Servicio o en cualquier p&aacute;gina web relacionada es inexacta en cualquier momento sin previo aviso (incluso despu&eacute;s de haber enviado su pedido).</p>
                <p>No asumimos ninguna obligaci&oacute;n de actualizar, modificar o aclarar la informaci&oacute;n en el Servicio o en cualquier sitio web relacionado, incluyendo de manera enunciativa pero no limitativa, la informaci&oacute;n de precios, excepto cuando lo exija la ley. Ninguna actualizaci&oacute;n especificada o fecha de actualizaci&oacute;n aplicada en el Servicio o en cualquier sitio web relacionado debe tomarse para indicar que toda la informaci&oacute;n en el Servicio o en cualquier sitio web relacionado se modific&oacute; o actualiz&oacute;.</p>
                <br>
                <p><strong>SECCI&Oacute;N 12: USOS PROHIBIDOS</strong></p>
                <p>Adem&aacute;s de las prohibiciones establecidas en los T&eacute;rminos del servicio, se le proh&iacute;be utilizar el sitio o su contenido (a) para cualquier prop&oacute;sito ilegal; (b) para solicitar a otros que realicen o participen en cualquier acto ilegal; (c) para infringir cualquier reglamento, norma, ley u ordenanza local internacional, federal, provincial o estatal; (d) para infringir o violar nuestros derechos de propiedad intelectual o los derechos de propiedad intelectual de otros; (e) acosar, abusar, insultar, da&ntilde;ar, difamar, calumniar, denigrar, intimidar o discriminar por motivos de g&eacute;nero, orientaci&oacute;n sexual, religi&oacute;n, etnia, raza, edad, nacionalidad o discapacidad; (f) enviar informaci&oacute;n falsa o enga&ntilde;osa;</p>
                <p>(g) cargar o transmitir virus o cualquier otro tipo de c&oacute;digo da&ntilde;ino que afecte o pueda afectar a la funcionalidad o el funcionamiento del Servicio o de cualquier sitio web relacionado, de otros sitios web o de Internet; (h) recopilar o rastrear la informaci&oacute;n personal de otros; (i) enviar correo no deseado, phishing, pharm, pretexto, spider, rastrear o extraer; (j) para cualquier prop&oacute;sito obsceno o inmoral; o (k) para interferir o eludir las funciones de seguridad del Servicio o de cualquier sitio web relacionado, o de otros sitios web o de Internet. Nos reservamos el derecho de dar por terminado su uso del Servicio o de cualquier sitio web relacionado por infringir cualquiera de los usos prohibidos.</p>
                <br>
                <p><strong>SECCI&Oacute;N 13: DESCARGO DE RESPONSABILIDAD DE GARANT&Iacute;AS; LIMITACI&Oacute;N DE RESPONSABILIDAD</strong></p>
                <p>No garantizamos, representamos ni aseguramos que el uso que haga de nuestro servicio ser&aacute; sin interrupciones, oportuno, seguro o sin errores.</p>
                <p>No garantizamos que los resultados que se puedan obtener del uso del servicio sean exactos o confiables.</p>
                <p>Usted acepta que peri&oacute;dicamente, podamos eliminar el servicio por lapsos de tiempo indefinidos o cancelar el servicio en cualquier momento, sin notificarle.</p>
                <p>Usted acepta expresamente que su uso del servicio o la imposibilidad de utilizarlo corre por su riesgo. El servicio y todos los productos y servicios que se le entregan a trav&eacute;s del servicio (salvo que as&iacute; lo especifiquemos nosotros) se ofrecen "tal como est&aacute;n" y "seg&uacute;n disponibilidad" para su uso, sin ninguna representaci&oacute;n, garant&iacute;a o condici&oacute;n de ning&uacute;n tipo, ya sea expresa o impl&iacute;cita, entre las que se incluyen todas las garant&iacute;as impl&iacute;citas o condiciones de comerciabilidad, calidad comercial, idoneidad para un prop&oacute;sito particular, durabilidad, t&iacute;tulo y no violaci&oacute;n.</p>
                <p>En ning&uacute;n caso CONFID, nuestros directores, funcionarios, empleados, afiliados, agentes, contratistas, pasantes, proveedores, proveedores de servicios o licenciantes ser&aacute;n responsables de cualquier lesi&oacute;n, p&eacute;rdida, reclamo o cualquier da&ntilde;o directo, indirecto, incidental, punitivo, especial o consecuente de cualquier tipo, incluyendo de manera enunciativa m&aacute;s no limitativa; la p&eacute;rdida de beneficios, p&eacute;rdida de ingresos, p&eacute;rdida de ahorros, p&eacute;rdida de datos, costos de reemplazo o da&ntilde;os similares, ya sea por contrato, perjuicio (incluida la negligencia), responsabilidad estricta o de otro tipo, que surjan del uso que haga de cualquiera de los servicios o de cualquier producto adquirido por medio del servicio, o para cualquier otro reclamo relacionado de alguna manera con su uso del servicio o de cualquier producto, incluidos, entre otros, cualquier error u omisi&oacute;n en cualquier contenido, o cualquier p&eacute;rdida o da&ntilde;o de cualquier tipo en el que se haya incurrido como resultado del uso del servicio o de cualquier contenido (o producto) publicado, transmitido o puesto a disposici&oacute;n a trav&eacute;s del servicio, incluso si se informa de su posibilidad.</p>
                <p>Debido a que algunos estados o jurisdicciones no permiten la exclusi&oacute;n o la limitaci&oacute;n de la responsabilidad por da&ntilde;os consecuentes o incidentales, en dichos estados o jurisdicciones, nuestra responsabilidad se limitar&aacute; a la extensi&oacute;n m&aacute;xima de lo permitido por la ley.</p>
                <br><p><strong>SECCI&Oacute;N 14: INDEMNIZACI&Oacute;N</strong></p>
                <p>Usted acepta indemnizar, defender y mantener indemne a CONFID y a nuestra empresa matriz, subsidiarias, afiliadas, asociados, funcionarios, directores, agentes, contratistas, licenciantes, proveedores de servicios, subcontratistas, proveedores, pasantes y empleados, de cualquier reclamo o demanda, incluidos los honorarios razonables de abogados, en los que un tercero haya incurrido debido a su incumplimiento de los presentes T&eacute;rminos del servicio o de los documentos que incorporan como referencia o que surjan por su incumplimiento de los mismos, o por la violaci&oacute;n de cualquier ley o derechos de un tercero que haga.</p>
                <br>
                <p><strong>SECCI&Oacute;N 15: DIVISIBILIDAD</strong></p>
                <p>En caso de que se determine que alguna disposici&oacute;n de los presentes T&eacute;rminos del servicio sea ilegal, nula o inaplicable, dicha disposici&oacute;n ser&aacute;, no obstante, ejecutable en la medida en que lo permita la legislaci&oacute;n aplicable, y la parte inaplicable se considerar&aacute; separada de los presentes T&eacute;rminos del servicio, sin que dicha determinaci&oacute;n afecte a la validez y aplicabilidad de las dem&aacute;s disposiciones.</p>
                <br><p><strong>SECCI&Oacute;N 16: RESCISI&Oacute;N</strong></p>
                <p>Las obligaciones y responsabilidades de las partes incurridas antes de la fecha de rescisi&oacute;n seguir&aacute;n vigentes despu&eacute;s de la rescisi&oacute;n de este contrato a todos los efectos.</p>
                <p>Estos T&eacute;rminos del servicio se encuentran vigentes a menos que usted o nosotros los rescindamos. Puede rescindir los presentes T&eacute;rminos del servicio en cualquier momento al notificarnos que ya no desea utilizar nuestros Servicios o cuando cese de utilizar nuestro sitio.</p>
                <p>Si a nuestro juicio usted incumple, o sospechamos que ha incumplido con cualquier t&eacute;rmino o disposici&oacute;n de los presentes T&eacute;rminos del servicio, podemos rescindir igualmente este acuerdo en cualquier momento sin previo aviso y usted seguir&aacute; siendo responsable de todos los importes adeudados, hasta la fecha de rescisi&oacute;n inclusive; y/o en consecuencia podemos denegarle el acceso a nuestros Servicios (o a parte de ellos).</p>
                <br><p><strong>SECCI&Oacute;N 17: ACUERDO COMPLETO</strong></p>
                <p>El hecho de que no ejerzamos o hagamos valer alg&uacute;n derecho o disposici&oacute;n de los presentes T&eacute;rminos del Servicio no constituir&aacute; una renuncia a dicho derecho o disposici&oacute;n.</p>
                <p>Estos T&eacute;rminos de servicio y cualquier pol&iacute;tica o regla de funcionamiento que hayamos publicado en este sitio o con respecto al Servicio constituye el acuerdo y el entendimiento completo entre usted y nosotros, y rigen su uso del Servicio, sustituyendo a cualquier acuerdo, comunicaci&oacute;n o propuesta anterior o contempor&aacute;nea, ya sea oral o escrita, entre usted y nosotros (incluyendo de manera enunciativa m&aacute;s no limitativa, las versiones anteriores de los T&eacute;rminos del servicio).</p>
                <p>Cualquier ambig&uuml;edad en la interpretaci&oacute;n de los presentes T&eacute;rminos del servicio no se interpretar&aacute; en contra de la parte redactora.</p>
                <br><p><strong>SECCI&Oacute;N 18: LEY APLICABLE</strong></p>
                <p>Los presentes T&eacute;rminos del servicio y cualquier acuerdo por separado por el cual le proporcionemos Servicios se regir&aacute;n e interpretar&aacute;n de acuerdo con las leyes de Carrer Marina, 150, Badalona, B, 08911 , Espa&ntilde;a.</p>
                <br><p><strong>SECCI&Oacute;N 19: CAMBIOS EN LOS T&Eacute;RMINOS DEL SERVICIO</strong></p>
                <p>Puede revisar la versi&oacute;n m&aacute;s reciente de los T&eacute;rminos del servicio en cualquier momento en esta p&aacute;gina.</p>
                <p>Nos reservamos el derecho, a nuestra entera discreci&oacute;n, de actualizar, cambiar o sustituir cualquier parte de los presentes T&eacute;rminos del servicio mediante la publicaci&oacute;n de actualizaciones y cambios en nuestro sitio web. Es su responsabilidad consultar nuestro sitio web peri&oacute;dicamente para ver los cambios. El uso que haga de nuestra p&aacute;gina web o del Servicio o su acceso a cualquiera de estos de forma continua despu&eacute;s de la publicaci&oacute;n de cualquier cambio en los presentes T&eacute;rminos del servicio, constituye la aceptaci&oacute;n de dichos cambios.</p>
                <br><p><strong>SECTION 20: INFORMACI&Oacute;N DE CONTACTO</strong></p>
                <p>Las preguntas sobre los T&eacute;rminos del servicio se deben enviar a info@confid.es.</p>
            </div>
        </div>
        <?php include_once $far.'php/comun/footer.php'; ?>
    </body>
</html>